version: "3.3"
services:
        mongo:
                image: mongo
                container_name: "mymongo"
                # ports:
                #  - "3456:27017"
                restart: always   
                environment:
                        MONGO_INITDB_ROOT_USERNAME: root
                        MONGO_INITDB_ROOT_PASSWORD: password
                        # MONGO_INITDB_DATABASE: weibo
                volumes:
                        - ./mongo_data:/data/db
        node:
                image: node:16
                container_name: "node-server"
                command: sh -c "npm config set registry https://registry.npm.taobao.org && npm install && npm start"
                #links:
                        # - mongo docker-compose自带网络，不用再单独设置
                restart: always
                ports:
                  - "3001:3001"
                working_dir: /usr/src/app    
                volumes:
                  - ./node:/usr/src/app
                depends_on:
                  - mongo
                environment:
                        SECRET: SOMETHING SECRET STRING ++11~~
                        PORT: 3001
                        #数据库必须要用@mongo地址，其它连不上，在工程里也是
                        MONGODB_URI: mongodb://root:password@mongo/weibo?authSource=admin
        nginx:
                image: nginx
                restart: always
                container_name: mynginx
                ports:
                  - "80:80"
                  - "443:443"
                volumes:
                  - ./dist:/usr/share/nginx/html
                  - ./nginx.conf:/etc/nginx/conf.d/default.conf 
                  - ./certs:/etc/nginx/certs 
